var challengeArray = [
"kahoot.gotten stuck with an elevator with a droid.",
"been invited to a wedding and only the droid was named on the invitation.",
"forgot to charge my batteries before an event?",
"Bragged about how my paint job looks.",
"Intentionally ran my droid into someone or something.",
"Laughed when I saw a droid fail to move.",
"(Follow up to last ) laughed when I saw a friend's droid fail to move.",
"cosplayed as Leia and knelt in front of R2.",
"cancelled on a date because your 30 hour print was almost finished.",
"had a print finish that only mm’s left on the roll.",
"heard of a T3",
"contemplated throwing my 3D printer out of the window",
"put my tool down and forgot where I put it",
"made a blood sacrifice to the gods",
"bet on droid racing",
"taken my droid with me in a public bathroom.",
"winced at seeing a droid crash",
"have a full conversation with my droid as if it was a real person",
"started another droid before finishing my current one",
"had dreams about my droid",
"wanted to shout at somebody for almost breaking my droid",
"scared a child with my droid",
"gotten through security because I was driving a droid.",
"been drunk whilst operating a droid either publicly or privately",
"had to go to the ER because of a droid related injury.",
"run over another droid builder.",
"run over myself with my droid",
"contemplated purposely running over an adult",
"compared my droid to another droid",
"pretended to be with a droid builder for the sake of a pretty woman.",
"bought a part for my droid then found a cheaper alternative",
"though my droid is the only one that gets me.",
"wondered if your droid would get stuck out on the hockey rink.",
"forgotten an important thing at an event",
"lied about how much I have spent on my droid to my wife/husband/partner/parents/dog",
"wondered why Lee Towersey slipped on that plank",
"thought about ditching all human contact to replace with more droids",
"thought about using a hammer to provide “gentle persuasion”",
"chased a kid with my droid.",
"purposely placed my droid in somebody's direct path of walking",
"cried while watching a star wars movie",
"covered mistakes with weathering",
"said a bad word during the entire droid building process",
"wondered where I am going to store my droid.",
"returned from an event/ builders meet highly motivated",
"had to drive around an event looking for a working elevator.",
"exaggerated parts of my build to a non-builder so I sound more clever",
"claimed a droid you were driving was not yours.",
"hated nature as much as when a fly/ bug lands on my still wet part",
"played the cantina song at an event and no one recognized it",
"worked on a droid while drunk.",
"donated a used printed part to a New Builder.",
"gotten my shadow controllers mixed up with other builders.",
"waited on my front porch for the UPS van to show up.",
"told a new builder to “register on the forum”",
"ordered parts and forgot about them until months later when they show up.",
"wished I was the boom mic guy in pink shorts.",
"thought Anakin's description of sand was spot on.",
"added vinyl tape to my R2-D2 because there were to many at an event",
"blamed a droid for a reason to break up with someone.",
"challenged a droid to a fight.",
"wished your R2-D2 (droid) was a battle bot.",
"had unintentional smoke come from my droid",
"wondered why I started this project",
"got my head stuck in a droid.",
"gone to the store, bought things, got home and then still forgot something",
"wanted James Earl Jones to narrate my life.",
"wondered why I took that call from Rob Howdle.",
"Never have wished I live in a country that could get Motip Filler Primer",
"used Dirty down as on a perfectly clean droid",
"stayed up late/ all night to finish one thing on your droid",
"wanted to stop building an astromech for a Wall-e.",
"got the same question from the public about how the head stays on.",
"had to ask for help putting my droid in my car",
"woken up every hour to check if your batteries are charged for an event.",
"looked at a droid and said “ Hot Damn look at those boosters! “",
"forgotten to charge my controller",
"had to answer the following questions: How long did it take you to build that? How much did you spend on it? Can you build me one?",
"gotten my droid mislabelled before.",
"gotten annoyed at droid continuity errors",
"said what print lines.",
"played inappropriate music from my droid.",
"gotten the horseshoe buttons the wrong way round",
"pulled the dome off my droid in public.",
"corrected someone about the correct way to say AT-AT",
"described the cost of something by using a phrase similar to “I could build … amount of droids for that!”",
"told my kids that My Lego is My Lego!",
"had to just walk away from a kid.",
"had a kid ask to drive my droid?",
"nearly crapped myself when an unsupervised child speeds towards my droid",
"had to convince someone that (Droid) is trade marked by George Lucas",
"nearly had a Droid Crash with somebody in a costume",
"thought that bb8 would make a great bowling ball.",
"had my holiday cards featured around my droids.",
"seen a post asking “Where can I find the plans/ files?”",
"Never would I ever think I would be trucking my droid across the country for an event.",
"Never would I ever build a droid based on how big my car was.",
"tried to give valid reasons for spending large amounts of money on something droid related",
"made the comment “I’m done after this droid“",
"had R2 as the best man or woman in my wedding.",
"been so happy to be part of the droid building community",
"said my droid is 100% done.",
"taken part in a Rob Quiz",
"challenged a Rob Quiz",
"built a Mr Baddeley Droid",
"finished printing version 1 only to see there is a version 2",
"face planted a droid",
"watch a droid be face planted",
"Never have I watched the legs come off a droid.",
"Never have I laughed when someone faceplanted a droid",
"Never have I wanted to run kids over with my droid.",
"dropped a screw into another dimension never to be seen again",
"Never have I wanted to build a T3. :)",
"stripped a bolt or screw trying to get it out.",
"spotted a problem and prayed that it fixed itself",
"Never have I said that “eh it’s good enough” when looking at my droid.",
"been able to put a USB in the correct way FIRST time",
"made it through an entire con without something breaking on my droid.",
"Never have I wanted to rebuild the droid right after finishing it.",
"had to buy new things solely for one part of your build",
"had a complete stranger make and 3d print a part to fix my droid overnight.",
"handed the controls to a non-droid builder and thought it was a good idea.",
"been told Rob is building a T3",
"told people I know celebrities when referring to droid builders involved in films",
"Never have I wanted Mr. B to stop designing droids too quickly.",
"drove my droid pass celebrity row and not though I would get a picture with them.",
"Never have I questioned that Rob was in fact building a T3.",
"wondered what Mr Baddeley does with all his failed prints?",
"Never have I wanted to be a member of the Les Towersey Official Fan Club.",
"believed that Rob did not get sick that night at R2UK.",
"3D Printed a part and then bought the same part in a different material",
"refused to buy something because I can 3D Print it",
"Never did I ever think a 3d print part looked better than an aluminium part.",
"had a random friend request from somebody with a droid builder mutual friend",
"been asked how much it costs to buy a droid?",
"had to clean a lipstick off my droid dome",
"wished I had a real taser in my droid",
"wanted to cry after spending so much on a droid.",
"been tempted to bill someone for damaging the droid",
"played a game with T3 in it",
"joined a droid building group and not build the droid",
"told Rob that the T3 is the best droid ever.",
"planned a vacation around a star wars celebration",
"bought something for my droid while being drunk.",
"wanted to go to Galaxys Edge to see how their droids is made",
"done a bad Star Wars Impression",
"laughed at Lee Towersey falling down a ramp.",
"based my new vehicle purchase on transporting a droid",
"printed non droid related things on my printer",
"witnessed a Star Wars wedding at a convention.",
"taken a picture of somebody elses camera to use as my Zoom Background",
"attended a Drinks and Droids After Party.",
"had a packing company pack my droid on the bottom.",
"greeted someone with the greeting “Hello There”",
"thought of moving house to so I can fit more droids in",
"got confused during my build",
"talked to a people more excited about star wars than me.",
"became friends with a builder that I have never met online",
"used random Star Wars Quotes in real life situations",
"used my Droid to get a “date”",
"waved my hands in front of an automatic door pretending to use the force to open them",
"played with a lightsaber and made the noises myself",
"made the PEW PEW sounds",
"argued/debated about who shot first",
"checked the weather before a droid event.",
"got upset when it started to rain during an event.",
"Never have I complained that George Lucas made to to many special editions",
"thought of Princess Leia while…. Taking some personal time.",
"made a comment about a Stormtroopers aim",
"add a porg to my droid for no reason.",
"wished George Lucas came back after the Disney purchase.",
"purchased unofficial star wars merchandise.",
"had to ask my other halves permission before doing something droid related",
"tried to hide my shipping boxes after buying too much filament.",
"wished I started with a Mouse Droid",
"bought a 3d printer just for a droid.",
"disliked a droid in the film then ended up building him later",
"built a droid and then changed his colour for no reason.",
"made a non cannon droid",
"gotten bored with Rob talking about a T3.",
"wished my droid would bring me a beer or drink.",
"wish my droid had Artificial Intelligence",
"started sentence with “According to Rob”",
"complained about robs typos.",
"had a failed print right before the end",
"had to ask somebody to print something for me",
"woken up to a spaghetti mess on my print bed",
"found I ran out of filament and my printer didn’t stop",
"hooked up the battery backwards.",
"wanted a bigger printer",
"wondered who built the gondola astromech droid.",
"had printer envy.",
"chosen to spend time on my droid over family/friends",
"complained about the Imperial/Metric system",
"heard the tragedy of Darth Plagueis the Wise",
"said “I love the holiday special”",
"gotten mad at the special editions/ blu-ray changes",
"song along when saga begins come on.",
"wished I could quit my job to build droids full time",
"looked on eBay for a R2-D2 for sale.",
"said “I am good” after drinking like Rob did at R2UK.",
"got “Order 66” at a fast food restaurant.",
"thought “I need to finish my droid”",
"wanted my own Baby Yoda/ The Child",
"cursed myself for having such little willpower to stop making Star Wars things",
"built an R2",
"told myself “I’ll only make one droid”",
"cursed Mr Baddeley for making droids quicker than I can print",
"had to upgrade my 3D Printer to get a good print out of it",
"played filament roulette, hoping I have enough for this print",
"joined countless groups and forums since starting a droid build",
"hid in Lee Towersey’s Bunker.",
"bought the R2-D2 suit.",
"had somebody enquire about starting a build only to have their other half say they’re not allowed.",
"thought robs quizzes were incorrect?",
"laughed at the fake news of “Rob throwing up at R2UK”",
"had somebody ask me to write them some code",
"seen a post/comment on Facebook asked for the STL for a model",
"laugh during a lockdown Droid Builder Zoom Meetin"
]

module.exports = {
  generateChallenge: function() {
    randomChallenge = "Never have I ever ";
    var randomArray = challengeArray[Math.floor(Math.random() * challengeArray.length)];
    return randomChallenge + randomArray;
  }
};
